# Generated by Django 4.2.2 on 2023-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_message_to_user_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail_address',
            field=models.EmailField(default='example@example.com', max_length=200),
        ),
    ]
